class ProfileData {
    id: number = 0;
    titletower: string = "";
    title: string = "";
    name: string = "";
    token: string = "";
    gskill: number = 0;
    dskill: number = 0;
    gskillnx: number = 0;
    dskillnx: number = 0;
    gskillex: number = 0;
    dskillex: number = 0;
    gskillmx: number = 0;
    dskillmx: number = 0;
    gskilltbre: number = 0;
    dskilltbre: number = 0;
    gskilltb: number = 0;
    dskilltb: number = 0;
    gskillall: number = 0;
    dskillall: number = 0;
    gclearlv: number = 0;
    dclearlv: number = 0;
    gclearnum: number = 0;
    dclearnum: number = 0;
    gfclv: number = 0;
    dfclv: number = 0;
    gfcnum: number = 0;
    dfcnum: number = 0;
    gexclv: number = 0;
    dexclv: number = 0;
    gexcnum: number = 0;
    dexcnum: number = 0;
    opencount: string = "";
    countall: number = 0;
    countgf: number = 0;
    countdm: number = 0;
    comment: string = "";
    updatetime: string = "";
    uptimelong: number = 0;
    pausetype: number = 0;
    pausedate: string = "";
}

export default ProfileData;